"""djcode.md — Project context file that persists across sessions.

Automatically saved on exit with:
- Project name, path, language detection
- Conversation summary (key topics, files touched)
- User preferences learned during session
- Agent results and findings

Loaded on startup to give DJcode context about the project.
Similar to Claude Code's CLAUDE.md but auto-generated.
"""

from __future__ import annotations

import os
import json
from datetime import datetime
from pathlib import Path
from typing import Any


CONTEXT_FILENAME = "djcode.md"
GLOBAL_CONTEXT = Path.home() / ".djcode" / "global_context.md"


def detect_project_info(cwd: str | None = None) -> dict[str, Any]:
    """Detect project type, language, and key files in the current directory."""
    cwd = cwd or os.getcwd()
    p = Path(cwd)

    info: dict[str, Any] = {
        "path": cwd,
        "name": p.name,
        "languages": [],
        "frameworks": [],
        "key_files": [],
    }

    # Language detection via config files
    detections = [
        ("pyproject.toml", "Python", ""),
        ("setup.py", "Python", ""),
        ("requirements.txt", "Python", ""),
        ("Cargo.toml", "Rust", ""),
        ("package.json", "JavaScript/TypeScript", ""),
        ("tsconfig.json", "TypeScript", ""),
        ("go.mod", "Go", ""),
        ("pom.xml", "Java", "Maven"),
        ("build.gradle", "Java", "Gradle"),
        ("Gemfile", "Ruby", ""),
        ("mix.exs", "Elixir", ""),
        ("composer.json", "PHP", ""),
    ]

    for filename, lang, framework in detections:
        if (p / filename).exists():
            if lang not in info["languages"]:
                info["languages"].append(lang)
            if framework:
                info["frameworks"].append(framework)
            info["key_files"].append(filename)

    # Framework detection
    framework_files = [
        ("next.config.js", "Next.js"), ("next.config.mjs", "Next.js"),
        ("next.config.ts", "Next.js"),
        ("vite.config.ts", "Vite"), ("vite.config.js", "Vite"),
        ("astro.config.mjs", "Astro"),
        ("docker-compose.yml", "Docker"), ("Dockerfile", "Docker"),
        (".github/workflows", "GitHub Actions"),
        ("tailwind.config.js", "Tailwind"), ("tailwind.config.ts", "Tailwind"),
        ("prisma/schema.prisma", "Prisma"),
        (".env", "Environment Variables"),
        (".gitignore", "Git"),
    ]

    for fname, fw in framework_files:
        target = p / fname
        if target.exists() or target.is_dir():
            if fw not in info["frameworks"]:
                info["frameworks"].append(fw)
            if fname not in info["key_files"]:
                info["key_files"].append(fname)

    return info


def load_context(cwd: str | None = None) -> str | None:
    """Load djcode.md from the current directory if it exists."""
    cwd = cwd or os.getcwd()
    ctx_file = Path(cwd) / CONTEXT_FILENAME
    if ctx_file.exists():
        try:
            return ctx_file.read_text(encoding="utf-8")[:8000]
        except OSError:
            return None
    return None


def save_context(
    cwd: str | None = None,
    *,
    model: str = "",
    provider: str = "",
    messages_count: int = 0,
    files_touched: list[str] | None = None,
    tools_used: list[str] | None = None,
    summary: str = "",
) -> str:
    """Save djcode.md to the current directory with session context.

    Returns the path where it was saved.
    """
    cwd = cwd or os.getcwd()
    ctx_file = Path(cwd) / CONTEXT_FILENAME

    project = detect_project_info(cwd)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Build the context file
    lines: list[str] = []
    lines.append(f"# DJcode Project Context")
    lines.append(f"")
    lines.append(f"> Auto-generated by DJcode on {now}")
    lines.append(f"> This file helps DJcode understand your project across sessions.")
    lines.append(f"> Edit it to add project-specific instructions.")
    lines.append(f"")
    lines.append(f"## Project")
    lines.append(f"- **Name:** {project['name']}")
    lines.append(f"- **Path:** {project['path']}")
    if project["languages"]:
        lines.append(f"- **Languages:** {', '.join(project['languages'])}")
    if project["frameworks"]:
        lines.append(f"- **Frameworks:** {', '.join(project['frameworks'])}")
    if project["key_files"]:
        lines.append(f"- **Key Files:** {', '.join(project['key_files'][:10])}")
    lines.append(f"")

    lines.append(f"## Last Session")
    lines.append(f"- **Date:** {now}")
    lines.append(f"- **Model:** {model}")
    lines.append(f"- **Provider:** {provider}")
    lines.append(f"- **Messages:** {messages_count}")
    if tools_used:
        lines.append(f"- **Tools Used:** {', '.join(set(tools_used))}")
    if files_touched:
        lines.append(f"- **Files Touched:** {', '.join(files_touched[:20])}")
    lines.append(f"")

    if summary:
        lines.append(f"## Session Summary")
        lines.append(summary)
        lines.append(f"")

    # Preserve user-added sections from existing file
    existing = load_context(cwd)
    if existing:
        # Find user sections (anything after "## Custom Instructions" or similar)
        for marker in ["## Custom Instructions", "## Notes", "## Rules", "## Preferences"]:
            idx = existing.find(marker)
            if idx >= 0:
                lines.append(existing[idx:].strip())
                break

    content = "\n".join(lines) + "\n"

    try:
        ctx_file.write_text(content, encoding="utf-8")
    except OSError:
        pass  # Permission denied or read-only filesystem

    return str(ctx_file)


def inject_context_into_prompt(system_prompt: str, cwd: str | None = None) -> str:
    """If djcode.md exists, inject its contents into the system prompt."""
    ctx = load_context(cwd)
    if ctx:
        return system_prompt + f"\n\n## Project Context (djcode.md)\n{ctx}"
    return system_prompt
